examples/error.sample
examples/errors.sample

FEXPCMN-2 - Migrate all the common resources to the export-common module

---

schemas/acquisitions/scheduleParameters.json

Unique identifier will be used for implementing reschedule and remove schedule logic
While …

[MODEXPS-42] - Add unique identifier to scheduleParameters.json

---

schemas/acquisitions/common/reference_number_item.json
schemas/acquisitions/mod-orders-storage/alert.json
schemas/acquisitions/mod-orders-storage/claim.json
schemas/acquisitions/mod-orders-storage/close_reason.json
schemas/acquisitions/mod-orders-storage/contributor.json
schemas/acquisitions/mod-orders-storage/cost.json
schemas/acquisitions/mod-orders-storage/details.json
schemas/acquisitions/mod-orders-storage/eresource.json
schemas/acquisitions/mod-orders-storage/fund_distribution.json
schemas/acquisitions/mod-orders-storage/license.json
schemas/acquisitions/mod-orders-storage/location.json
schemas/acquisitions/mod-orders-storage/ongoing.json
schemas/acquisitions/mod-orders-storage/physical.json
schemas/acquisitions/mod-orders-storage/product_identifier.json
schemas/acquisitions/mod-orders-storage/reporting_code.json
schemas/acquisitions/mod-orders-storage/vendor_detail.json
schemas/acquisitions/mod-orders/composite_po_line.json
schemas/acquisitions/mod-orders/composite_purchase_order.json

https://issues.folio.org/browse/MODEXPW-41
added acq models required for composite PO
While …

MODEXPW-40 - acq models required for composite PO

---

schemas/acquisitions/scheduleParameters.json

Add exact date schedule and time zone fields
While it's helpful for reviewers to help …

[MODEXPS-54] - Add exact date schedule and time zone fields

---

schemas/acquisitions/ediConfig.json
schemas/acquisitions/ediSchedule.json
schemas/acquisitions/scheduleParameters.json
schemas/acquisitions/vendorEdiOrdersExportConfig.json

[MODEXPS-42] - Update acq schedule module

---

schemas/acquisitions/vendorEdiOrdersExportConfig.json

There is requirements to search EDI export jobs by configuration UUID.
While it's helpful …

[MODEXPS-62] - Add export config reference in the EDI export config

---

schemas/acquisitions/ediFtp.json
schemas/acquisitions/mod-orders-storage/export_history.json
schemas/acquisitions/mod-orders-storage/po_line.json
schemas/acquisitions/mod-orders-storage/po_line_collection.json
schemas/acquisitions/mod-orders-storage/purchase_order.json
schemas/acquisitions/mod-orders-storage/purchase_order_collection.json

MODEXPW-42 add export history schema

---

schemas/acquisitions/common/reference_number_item.json

https://issues.folio.org/browse/MODEXPW-42
* openapi does not support javaEnum type. updated enum definition
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODEXPW-42 vendor detail enum fixed

---

schemas/bulk-edit/identifierType.json

[FEXPCMN-3](https://issues.folio.org/browse/FEXPCMN-3) - Update schemas to support item retrieval
In order to support item retrieval, the following schema changes are required:
1. Enrich enums in entityType and identifierType schemas with new values:
entityType: "ITEM"
identifierType: "HRID", "FORMER_IDS", "ACCESSION_NUMBER", "HOLDINGS_RECORD_ID"
2. Add schemas for item and item collection
* Updated schemas
- Are the JIRAs under …

FEXPCMN-3 - Update schemas to support item retrieval

---

schemas/inventory/briefHoldingCollection.json
schemas/inventory/briefInstanceCollection.json
schemas/inventory/callNumberTypeCollection.json
schemas/inventory/damagedStatusCollection.json
schemas/inventory/electronicAccessRelationshipCollection.json
schemas/inventory/itemNoteTypeCollection.json
schemas/inventory/loanTypeCollection.json
schemas/inventory/locationCollection.json
schemas/inventory/materialTypeCollection.json
schemas/inventory/statisticalCodeCollection.json

[FEXPCMN-4](https://issues.folio.org/browse/FEXPCMN-4) - Update schemas to support bulk-edit item update
In order to support bulk-edit item update, the following schemas need to be added:
* BriefHoldingCollection
* BriefInstanceCollection
* CallNumberTypeCollection
* DamagedStatusCollection
* ElectronicAccessRelationshipCollection
* ItemNoteTypeCollection
* LoanTypeCollection
* LocationCollection
* MaterialTypeCollection
* StatisticalCodeCollection
* Added schemas
- Do JIRAs …

FEXPCMN-4 - Update schemas to support bulk-edit item update

---

examples/bulk-edit/contentUpdate.sample
examples/bulk-edit/contentUpdateCollection.sample
schemas/bulk-edit/contentUpdate.json
schemas/bulk-edit/contentUpdateCollection.json

[FEXPCMN-5](https://issues.folio.org/browse/FEXPCMN-5) - Create schemas for bulk-edit content update

FEXPCMN-5 - Create schemas for bulk-edit content update

---

schemas/acquisitions/ediConfig.json
schemas/acquisitions/ediFtp.json

LibEdiCode or LibEdiType or VendorEdiCode or VendorEdiType should be required
While it's …

[MODEXPW-102] - Added required fields

---

schemas/eholdings/eHoldingsExportConfig.json

Instead of using query to search is better to get packages and related titles by packageId

MODEXPS-94 Edit eholdings export config

---

schemas/eholdings/eHoldingsExportConfig.json

MODEXPS-94 Add enum recordType for eHoldings

---

schemas/acquisitions/ediConfig.json
schemas/acquisitions/ediFtp.json

[MODEXPW-102] - Deleted required fields

---

schemas/bulk-edit/identifierType.json

[FEXPCMN-7](https://issues.folio.org/browse/FEXPCMN-7) - Extend IdentifierType schema

FEXPCMN-7 - Extend IdentifierType schema

---

schemas/bulk-edit/itemContentUpdate.json

[FEXPCMN-15](https://issues.folio.org/browse/FEXPCMN-15) - Bulk edit: Item loan types - Update schemas
In order to support item loan types updates, option enum in ItemContentUpdate schema should be enriched with new values:
* PERMANENT_LOAN_TYPE
* TEMPORARY_LOAN_TYPE
* ItemContentUpdate schema updated
Ideally all of the PRs involved in breaking changes …

FEXPCMN-15 - Bulk edit: Item loan types - Update schemas

---

schemas/inventory/holdingsNoteTypeCollection.json
schemas/inventory/holdingsRecordCollection.json

[FEXPCMN-14](https://issues.folio.org/browse/FEXPCMN-14) - Bulk edit: holdings locations - Update schemas
Bulk edit schemas should be updated to support holdings records.
* minor improvements
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

FEXPCMN-14 - Bulk edit: holdings locations - Update schemas

---

schemas/acquisitions/mod-orders-storage/export_history.json

[MODEXPW-240]-modified export_history.json

---

schemas/acquisitions/mod-orders-storage/export_history.json

[MODEXPW-273]-added "jobName" field

---

schemas/eholdings/e-provider/provider.json
schemas/eholdings/e-provider/providerAttributes.json
schemas/eholdings/e-provider/providerData.json

[MODEXPW-273]-added missing files

---

schemas/exportFilePresignedUrl.json

Add  presignedUrl schema
While it's helpful for reviewers to help identify potential …

[MODEXPW-330] - Added exportFilePresignedUrl schema

---

schemas/authoritycontrol/authorityControlExportConfig.json
schemas/exportType.json
schemas/exportTypeSpecificParameters.json

Add entities for Authority Control export
- add export types
- add new export config
- add new config to exportTypeSpecificParameters.json
[FEXPCMN-16](https://issues.folio.org/browse/FEXPCMN-16)

FEXPCMN-16 Authority control: add new export type

---

schemas/bulk-edit/entityType.json
schemas/bulk-edit/identifierType.json
schemas/inventory-storage/classificationType.json
schemas/inventory-storage/contributorNameType.json
schemas/inventory-storage/formatOfInstance.json
schemas/inventory-storage/instance.json
schemas/inventory-storage/instanceCollection.json
schemas/inventory/formatOfInstance.json
schemas/inventory/instanceStatus.json
schemas/inventory/instanceType.json
schemas/inventory/issuanceMode.json
schemas/inventory/natureOfContentTerm.json

MODEXPW-452: Retrieve instance records for bulk edit.

---

schemas/user/personal.json

[MODEXPW-463](https://folio-org.atlassian.net/browse/MODEXPW-463) - User schema update
User schema (folio-export-common) should be updated to reflect changes https://github.com/folio-org/mod-users/blob/8b8ae858dcc0217fa65243de014a509aedd32bc4/ramls/userdata.json#L149 
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

MODEXPW-463 - User schema update

---

schemas/user/customFieldTypes.json

MODEXPW-463 - update custom field types

---

schemas/inventory/instanceNoteType.json
schemas/inventory/instanceNoteTypeCollection.json

[MODEXPW-478](https://folio-org.atlassian.net/browse/MODEXPW-478) - Add notes field to instance csv file

MODEXPW-478 - Add notes field to instance csv file

---

schemas/consortia/userTenant.json
schemas/consortia/userTenantCollection.json
schemas/search/batchIds.json
schemas/search/consortiumHolding.json
schemas/search/consortiumHoldingCollection.json
schemas/search/consortiumItem.json
schemas/search/consortiumItemCollection.json

[MODEXPW-477](https://folio-org.atlassian.net/browse/MODEXPW-477) - Items and holdings tenant populating
Updating schemas for feature implementation. It is required by [MODEXPW-477](https://folio-org.atlassian.net/browse/MODEXPW-477).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODEXPW-477 - Items and holdings tenant populating (folio-export-common schemas bump up)

---

schemas/search/batchIds.json
schemas/search/consortiumHoldingCollection.json
schemas/search/consortiumItemCollection.json

[MODEXPW-477](https://folio-org.atlassian.net/browse/MODEXPW-477) - Items and holdings tenant populating
* Fixed schemas
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODEXPW-477 - Items and holdings tenant populating

---

schemas/inventory/holdingsRecordsSource.json

[MODEXPW-498](https://folio-org.atlassian.net/browse/MODEXPW-498) - HoldingsRecordsSource schema alignment
Schema [folio-export-common/schemas/inventory/holdingsRecordsSource.json at master · folio-org/folio-export-common](https://github.com/folio-org/folio-export-common/blob/master/schemas/inventory/holdingsRecordsSource.json) should be aligned with [mod-inventory-storage/ramls/holdings-sources/holdingsRecordsSource.json at master · folio-org/mod-inventory-storage](https://github.com/folio-org/mod-inventory-storage/blob/master/ramls/holdings-sources/holdingsRecordsSource.json) .
If there are …

MODEXPW-498 - HoldingsRecordsSource schema alignment

---

schemas/consortia/userTenant.json
schemas/search/consortiumHolding.json
schemas/search/consortiumItem.json

[MODEXPW-489](https://folio-org.atlassian.net/browse/MODEXPW-489) - Remove unused updating functionality
* fixed schemas for api-lint check
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

MODEXPW-489 - Remove unused updating functionality

---

schemas/inventory-storage/instance.json

[FEXPCMN-22](https://folio-org.atlassian.net/browse/FEXPCMN-22) - Add missing instance subject fields
Instance schema should be enriched with the following subject fields: sourceId, typeId (both strings).
* Updated instance schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

FEXPCMN-22 - Add missing instance subject fields

---

schemas/inventory-storage/instance.json

[MODEXPW-505](https://folio-org.atlassian.net/browse/MODEXPW-505) - API version update
Aligning instances schema relative to mod-inventory API.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

MODEXPW-505 - Aligning instances schema relative to mod-inventory API

---

schemas/inventory-storage/instance.json

[MODEXPW-505](https://folio-org.atlassian.net/browse/MODEXPW-505) - API version update
Apply formatter for schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

MODEXPW-505 - Aligning instances schema relative to mod-inventory API (schema formatting)

---

schemas/inventory-storage/instance.json

[MODEXPW-505](https://folio-org.atlassian.net/browse/MODEXPW-505) - API version update
Aligning instances schema relative to mod-inventory API.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

MODEXPW-505 - Aligning instances schema relative to mod-inventory API (partiall revert)

---

schemas/acquisitions/vendorEdiOrdersExportConfig.json

https://folio-org.atlassian.net/browse/MODEXPS-273
Add claimPieceIds for request payload to be used in Claiming export jobs

MODEXPS-277. Add claimPieceIds for ClaimingIntegration type

---

schemas/acquisitions/mod-orders-storage/piece.json
schemas/acquisitions/mod-orders-storage/piece_collection.json

[[MODEXPW-528] Generate EDI file for claims](https://folio-org.atlassian.net/browse/MODEXPW-528)
- Add Piece and PieceCollection for fetching Claims

[MODEXPW-528] Generate EDI file for claims

---

schemas/inventory/statisticalCodeType.json

[MODEXPW-548](https://folio-org.atlassian.net/browse/MODEXPW-548) - Add Statistical code column to Instance records preview
Add missing statisticalCodeType.json.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

MODEXPW-548 - Add Statistical code column to Instance records preview

---

schemas/inventory/subjectSource.json
schemas/inventory/subjectSourceCollection.json
schemas/inventory/subjectType.json
schemas/inventory/subjectTypeCollection.json

[MODEXPW-573](https://folio-org.atlassian.net/browse/MODEXPW-573) - Rendering Instance record Subjects in UI and downloadable files
Schemas needs to subject processing are added.
Subject source and type schemas are added.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

MODEXPW-573 - Rendering Instance record Subjects in UI and downloadable files

---

schemas/acquisitions/mod-orders-storage/eresource.json

[MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
- Updated the schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …

[MODORDSTOR-448] Change type of eresource.userLimit to string
